vm_template: ceph-node-1
vm_prefix: vm
source: roma
destination_1: milano
destination_2: roma
destination_3: palermo
pool_rbd: rbd
source_rbd_os: base-101-disk-0
num_vms_host: 2
snap_name: vm-os-boot-0
osds_per_node: 4
osd_size: 10000