service_type: host
addr: 192.168.1.102
hostname: ceph-osd-2
labels:
- mon
- osd
- mgr
---
service_type: host
addr: 192.168.1.103
hostname: ceph-osd-3
labels:
- mon
- osd
- mgr
---
service_type: host
addr: 192.168.1.104
hostname: ceph-osd-4
labels:
- osd
---
service_type: host
addr: 192.168.1.105
hostname: ceph-osd-5
labels:
- osd
---
service_type: host
addr: 192.168.1.106
hostname: ceph-osd-6
labels:
- osd